name: Compile Handbook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-linux-x86_64.tar.gz
          tar -xzf typst-linux-x86_64.tar.gz
          sudo mv typst /usr/local/bin/
          typst --version

      - name: Compile document
        run: |
          python make.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-document
          path: notebook.pdf
