name: Compile Handbook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ --strip-components=1
          sudo install -m 755 typst /usr/local/bin/
          typst --version

      - name: Install dependencies (fontconfig)
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig

      - name: Compile document
        run: |
          python make.py

      - name: Upload PDF (uncompressed)
        uses: actions/upload-pages-artifact@v3
        with:
          name: notebook.pdf
          path: notebook.pdf
